apiVersion: v1
kind: Service
metadata:
  namespace: s3-bucket-content
  name: vote-back
  labels:
    name: vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: vote-back
---
apiVersion: v1
kind: Service
metadata:
  namespace: s3-bucket-content
  name: vote-front
  labels:
    name: vote-front
spec:
  ports:
  - port: 80
  selector:
    app: vote-front