apiVersion: v1
kind: Service
metadata:
  name: vote-back-s3-bucket-content
  labels:
    name: vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: vote-back
---
apiVersion: v1
kind: Service
metadata:
  name: vote-front-s3-bucket-content
  labels:
    name: vote-front
spec:
  ports:
  - port: 80
  selector:
    app: vote-front